extends: ../defaults.yaml
devices:
  preferred_driver:
    windows: asio
    macos: coreaudio
  buffer_samples:
    min: 128
    fallback: 256
gate:
  look_ahead_ms: 12
  attack_ms: 18
  release_ms: 200
  hold_ms: 180
  duck_db: -18
logging:
  path:
    windows: "%APPDATA%/SingWithMe/logs"
    macos: "~/Library/Application Support/SingWithMe/logs"
