sample_rate_hz: 48000
buffer_samples: 128
vad:
  model_path: models/vad.onnx
  frame_ms: 10
pitch:
  model_path: models/crepe_tiny.onnx
  hop_ms: 20
confidence_weights:
  vad: 0.6
  pitch: 0.4
  phrase_aware: 0.0
gate:
  look_ahead_ms: 10
  attack_ms: 20
  release_ms: 180
  hold_ms: 150
  threshold_on: 0.7
  threshold_off: 0.4
  frames_on: 3
  frames_off: 6
  duck_db: -18
ui:
  theme:
    background: "#121212"
    accent_active: "#6BFF6B"
    accent_idle: "#FFC857"
  manual_modes: ["auto", "always_on", "always_off"]
logging:
  enabled: true
  file_rollover_minutes: 15
  include_latency_metrics: true
