name: CI

on:
  push:
    branches:
      - main
      - develop
      - "feature/**"
  pull_request:

jobs:
  web:
    name: Web Lint & Build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: web
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Enable Corepack
        run: corepack enable
      - name: Install dependencies
        run: pnpm install
      - name: Lint
        run: pnpm lint
      - name: Build
        run: pnpm build

  desktop-configure:
    name: Desktop CMake Configure
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install build tools
        run: sudo apt-get update && sudo apt-get install -y ninja-build
      - name: Configure CMake
        run: cmake -S desktop -B build/desktop -G Ninja -DENABLE_ONNX_RUNTIME=OFF -DCMAKE_BUILD_TYPE=Release
